package common.constants;

public enum ErrorCode {
	
	QUEUE_ADD, QUEUE_REMOVE, QUEUE_ADD_MULTIPLE, QUEUE_REMOVE_MULTIPLE,
	COMMAND_EXECUTION,
	FILE_READ, FILE_WRITE, FILE_APPEND,
	COMMAND_OUTPUT_LIST_PROCESS

}
